### PR TITLE
Remove basepath from mountpoint

### LINKED ISSUE #257: [BUG] Pot mount path is broken after importing an image and cloning it
**Describe the bug**
After importing and image with the mount point set you end up with a double path and start then fail. I've noticed there is something about fscomp.conf mentioned in the import code that it's unhandled. 

Before I go into what I've done I would like to know the reason of using the full path for the mount point inside of the pot. I've done a few changes in `_mount_dir` and `_pot_mount` so that when issuing

```
pot mount-in -v -p foo -d /usr/local/etc -m /bar/etc
```

store the value in fscomp.conf with the actual value set via the command and then while mounting add prefix on the fly.

This can then help when exporting and importing since the path can stay as it is. I can make a PR with my changes but would like to first understand if that even makes sense and if this long path in fscomp.conf was actually intentional. Btw, I've not done any research for data sets yet, but I would believe it should work the same way. Also this was only tested for pot that is in running state.

The change I did is visible https://github.com/urosgruber/pot/commit/57af9f2ea6377ea2eac43f1ad897042024cc3a91

### PR DESCRIPTION
**Pull request by urosgruber**
There are a couple of things that changed here

1. update the mount method to append the actual jail root path
2. update how mount-in stores the path without prefixing with the jail root path
3. fix clone to copy file since no need to fix anything

The missing bit is probably to remove two lines from rename command because no replacement is required. 

I haven't checked if anything breaks with the datasets.

But the process of creating pot, with some mounts, exporting it, and then import with additional clone makes everything as it should be.

This fixes #257

### CODE REVIEW

**Comment by pizzamig** [comment]
Hi. I like this approach, it makes the code simpler.
Need to run few tests with it, but it seems a good idea

**Comment by pizzamig** [comment]
I've pushed several changes, but I'd like to do more tests before to commit it

File: share/pot/clone.sh [hunk 1]
```diff
@@ -80,6 +80,7 @@ _cj_zfs()
 		rm -f "$_pdir/conf/fscomp.conf"
 	fi
 	_debug "Cloning $_potbase with snap $_snap"
+	_update_fscomp "$_potbase"
```
Comment (grembo) [inline share/pot/clone.sh:83]: The one thing I'm not so sure about is that it seems like the clone command now "fixes" the existing potbase. From a user perspective, I would be surprised that cloning an image actually changes the image it is cloning from.

**Review by grembo — COMMENTED** [review]
@urosgruber I think this is a great contribution, I only have some doubts about the "silent" migrations of existing pots (this could be confusing to users). _Update: Seems like the migration was added by @pizzamig :D_

@bretton @hny-gd @pizzamig Does one of happen to have the time to also look at this/give feedback/input.

File: share/pot/clone.sh (hunk 1 above)
Comment (pizzamig) [reply share/pot/clone.sh:83]: IIRC, this is to ensure that `clone`with the new layout is automatically updating the old one. It's only a configuration file, tho.
It's in the spirit of `update-config`, to ensure that configuration files evolve consistently when introducing a breaking change.
do you have a better approach? I'm not super happy with that, but it was the best thing I had in mind

Comment (grembo) [reply share/pot/clone.sh:83]: What about the following logic:

Replace

```
cp "${_pbdir}/conf/fscomp.conf" "$_pdir/conf/fscomp.conf"
```

With something like:

```
< "${_pbdir}/conf/fscomp.conf"  sed "s|^${POT_FS_ROOT}/jails/$_pname/m|g" >"$_pdir/conf/fscomp.conf"
```

And only actually clean up the fscomp.conf file whenever `update-config`, `mount-in` or `mount-out` are called.
(in which case the check if it's an old format won't be necessary, as you could simply always apply the filtering sed command from above to a temp file, append/remove the  mountpoint if necessary and then move the new file into place)

**Comment by bretton** [comment]
> @bretton @hny-gd @pizzamig Does one of happen to have the time to also look at this/give feedback/input.

I've done a test building a cluster environment using files from the PR, and all is working fine

File: share/pot/clone.sh (hunk 1 above)
Comment (pizzamig) [reply share/pot/clone.sh:83]: I like your approach. For `clone` is indeed not intuitive to change the base.
I'll follow your suggestion and changing paths on the fly

Comment (grembo) [reply share/pot/clone.sh:83]: @pizzamig Are you currently working on this, or should I give it a shot?

**Comment by grembo** [comment]
@bretton @hny-gd @pizzamig Hi guys, what about finishing this?

**Comment by pizzamig** [comment]
Hi. It works for me as well
