### PR TITLE
The current sed script delete everything

### LINKED ISSUE #224: [BUG] Unstoppable pot left over by nomad
**Describe the bug**
When running a pot via nomad and this pot fails, the pot is not cleaned out automatically.
Even trying directly to stop the pot via the CLI does not work.
The error I get when trying to stop the pot is:
```
$ sudo pot stop example_d5e017fb-1814-6e7e-dfa6-7947df66af7b -v
###>  pot example_d5e017fb-1814-6e7e-dfa6-7947df66af7b is not in a state where it can be stopped
```

```
$ pot version
pot version: 0.15.0
```

**To Reproduce**
1. Create the "defective" `pot` with nomad
2. pot fails to run
3. stop nomad job (with or without purge)
4. Run this command: ''sudo pot stop -p potname"
5. See error.

**Expected behavior**
The pot should be stopped and set to prune once nomad job is stopped. It would also be nice if the error explained why the pot can not be stopped.

**Debugging***
set -x on pot stop
```
+ grep '^pot.type=' /opt/pot/jails/example_d5e017fb-1814-6e7e-dfa6-7947df66af7b/conf/pot.conf
+ tr -d ' \t"'
+ cut -f2 '-d='
+ _value=single
+ echo single
+ _type=single
+ [ -z single ]
+ echo single
+ [ single '=' multi ]
+ return 0
+ _is_uid0
+ id -u
+ [ 0 '=' 0 ]
+ return 0
+ lockf /tmp/pot-lock-example_d5e017fb-1814-6e7e-dfa6-7947df66af7b /usr/local/bin/pot set-status -p example_d5e017fb-1814-6e7e-dfa6-7947df66af7b -s stopping
+ rc=1
+ [ 1 -eq 2 ]
+ [ 1 -eq 1 ]
+ _error 'pot example_d5e017fb-1814-6e7e-dfa6-7947df66af7b is not in a state where it can be stopped'
+ _msg 0 'pot example_d5e017fb-1814-6e7e-dfa6-7947df66af7b is not in a state where it can be stopped'
+ local _sev
+ _sev=0
+ shift
+ [ 0 -gt 1 ]
+ echo '###> ' 'pot example_d5e017fb-1814-6e7e-dfa6-7947df66af7b is not in a state where it can be stopped'
###>  pot example_d5e017fb-1814-6e7e-dfa6-7947df66af7b is not in a state where it can be stopped
+ exit 1
```
According to this it is failing on: 
```
lockf /tmp/pot-lock-example_d5e017fb-1814-6e7e-dfa6-7947df66af7b /usr/local/bin/pot set-status -p example_d5e017fb-1814-6e7e-dfa6-7947df66af7b -s stopping
```

Set -x on set-status:
```
+ _func=pot-set-status
+ logger -p local2.info -t pot 'pot-set-status -p example_d5e017fb-1814-6e7e-dfa6-7947df66af7b -s stopping'
+ pot-set-status -p example_d5e017fb-1814-6e7e-dfa6-7947df66af7b -s stopping
+ local _pname _new_status _current_status _conf
+ _pname=''
+ _new_status=''
+ OPTIND=1
+ getopts hvp:s: _o
+ _pname=example_d5e017fb-1814-6e7e-dfa6-7947df66af7b
+ getopts hvp:s: _o
+ _is_in_list stopping starting started stopping stopped
+ local _e
+ [ 5 -lt 2 ]
+ _e=stopping
+ shift
+ [ stopping '=' starting ]
+ [ stopping '=' started ]
+ [ stopping '=' stopping ]
+ return 0
+ _new_status=stopping
+ getopts hvp:s: _o
+ [ -z example_d5e017fb-1814-6e7e-dfa6-7947df66af7b ]
+ _is_pot example_d5e017fb-1814-6e7e-dfa6-7947df66af7b
+ local _pname _pdir
+ _pname=example_d5e017fb-1814-6e7e-dfa6-7947df66af7b
+ _pdir=/opt/pot/jails/example_d5e017fb-1814-6e7e-dfa6-7947df66af7b
+ [ ! -d /opt/pot/jails/example_d5e017fb-1814-6e7e-dfa6-7947df66af7b ]
+ _zfs_dataset_valid zroot/pot/jails/example_d5e017fb-1814-6e7e-dfa6-7947df66af7b
+ [ -z zroot/pot/jails/example_d5e017fb-1814-6e7e-dfa6-7947df66af7b ]
+ zfs list -o name -H zroot/pot/jails/example_d5e017fb-1814-6e7e-dfa6-7947df66af7b
+ [ zroot/pot/jails/example_d5e017fb-1814-6e7e-dfa6-7947df66af7b '=' zroot/pot/jails/example_d5e017fb-1814-6e7e-dfa6-7947df66af7b ]
+ return 0
+ [ ! -d /opt/pot/jails/example_d5e017fb-1814-6e7e-dfa6-7947df66af7b/m ]
+ [ ! -r /opt/pot/jails/example_d5e017fb-1814-6e7e-dfa6-7947df66af7b/conf/pot.conf ]
+ _get_pot_type example_d5e017fb-1814-6e7e-dfa6-7947df66af7b
+ local _type
+ _get_conf_var example_d5e017fb-1814-6e7e-dfa6-7947df66af7b pot.type
+ local _pname _cdir _var _value
+ _pname=example_d5e017fb-1814-6e7e-dfa6-7947df66af7b
+ _cdir=/opt/pot/jails/example_d5e017fb-1814-6e7e-dfa6-7947df66af7b/conf
+ _var=pot.type
+ grep '^pot.type=' /opt/pot/jails/example_d5e017fb-1814-6e7e-dfa6-7947df66af7b/conf/pot.conf
+ tr -d ' \t"'
+ cut -f2 '-d='
+ _value=single
+ echo single
+ _type=single
+ [ -z single ]
+ echo single
+ [ single '=' multi ]
+ return 0
+ _get_status example_d5e017fb-1814-6e7e-dfa6-7947df66af7b
+ local _pname _status_file
+ _pname=example_d5e017fb-1814-6e7e-dfa6-7947df66af7b
+ _status_file=/tmp/pot_status_example_d5e017fb-1814-6e7e-dfa6-7947df66af7b
+ [ ! -e /tmp/pot_status_example_d5e017fb-1814-6e7e-dfa6-7947df66af7b ]
+ grep '^pot.status=' /tmp/pot_status_example_d5e017fb-1814-6e7e-dfa6-7947df66af7b
+ tail -n 1
+ cut -f2 '-d='
+ tr -d ' \t"'
+ _value=''
+ echo ''
+ _current_status=''
+ [ '' '=' stopping ]
+ [ '' '!=' started ]
+ [ '' '!=' stopped ]
+ return 1
+ exit 1
```

### PR DESCRIPTION
**Pull request by pizzamig**
This easy fix, while not super robust, seems a first good patch

fix #224

### CODE REVIEW

**Comment by grembo** [comment]
strange, I'll take a look as well

**Comment by grembo** [comment]
Oh my - it only deletes the first appearance. Unfortunately, the first time status is written, there is only one appearance.
The easiest fix would be to always write the status twice.

File: share/pot/set-status.sh [hunk 1]
```diff
@@ -43,9 +43,13 @@ _set_status()
 
 	echo "pot.status=$_new_status" >> "$_status_file"
 	# remove first (and outdated) occurrence of pot.status
-	${SED} -i '' -n -e ":a" \
-		-e '/^pot\.status=/{n;bc' -e ':c' -e 'p;n;bc' -e '}' \
-		-e "p;n;ba" "$_status_file"
+	if [ "$(grep -c "^pot\.status=" "$_status_file")" -gt 1 ]; then
+		${SED} -i '' -e '1d' "$_status_file"
```
Comment (grembo) [inline share/pot/set-status.sh:47]:
```suggestion
	${SED} -i '' -n -e ":a" \
		-e '/^pot\.status=/{n;bc' -e ':c' -e 'p;n;bc' -e '}' \
		-e "p;n;ba" "$_status_file"'
```

This (combined with your new check) should work fine. It always removes the first status line (but it doesn't figure out that there is only one, which is what your grep fixes now). >_<

**Comment by pizzamig** [comment]
If you agree, I'll do an emergency release for conference reasons.
A more robust patch can come later

**Review by grembo — CHANGES_REQUESTED** [review]

**Comment by grembo** [comment]
> If you agree, I'll do an emergency release for conference reasons. A more robust patch can come later

I can test the proposed patch right away, should work just fine, but I can confirm in a few minutes.

**Comment by pizzamig** [comment]
Just updated the patch to call sed only if there are multiple entries

**Comment by grembo** [comment]
So the patch seems to work. But there are more problems. I'll elaborate in a second.

**Comment by pizzamig** [comment]
Technically, we can rework it to overwrite the entire file with the last entry available (like get_status)

**Comment by grembo** [comment]
```
# pot start cloneme
###>  No ipv4 address found for cloneme
###>  pot cloneme is not in a state where it can be stopped
# pot show
# cat /tmp/pot_status_cloneme
pot.status=starting
# pot set-status -p cloneme -s stopping || echo "PROBLEM"
PROBLEM
# pot set-status -p cloneme -s started || echo "PROBLEM"
# pot set-status -p cloneme -s stopped || echo "PROBLEM"```
```
So basically, problems during start keep the pot stuck in "starting", since it can't go from "starting" directly to "stopping".

**Comment by grembo** [comment]
> Technically, we can rework it to overwrite the entire file with the last entry available (like get_status)

No, the patch is fine and solves the issue at hand. We have an unrelated problem in the logic (see details above).
IMHO this patch can land now and we can resolve the other issue in a separate PR.

**Review by grembo — APPROVED** [review]
This fixes the problem described, but a separate issue persists.

**Comment by pizzamig** [comment]
I see your point

**Comment by grembo** [comment]
So basically "start-cleanup" calls "pot stop" and if the pot hasn't _started_ yet, it can't stop (stopping->stopped).

**Comment by grembo** [comment]
I think the cleanest solution would be a new status like "doa" and allow to go from "doa" to stopping as well (just like from started).

**Comment by grembo** [comment]
Patch incoming...
