### PR TITLE
Start stop mutex

### LINKED ISSUE #202: [BUG] pot-stop, called from pot-start, might operate on the wrong jail.
**Describe the bug**
Calls to `pot-stop <jailname>` from pot-start might operate on the wrong jail.

This is part of why #200 fixed nomad problems, as a jail that was restarted, was partially dismantled by pot-stop called from pot-start. With #200 this is less of a problem, as each pot gets a truly unique name. It might be a problem with non-nomad jails though.

It seems like that this might also be the underlying reason why I perceived  behavior that made me create #201.

**To Reproduce**
1. Create a non-persistent pot using sleep <something> as the pot-cmd
2. Start that pot just at the right moment so that the invocations overlap
3. Perceive undefined behavior

**Expected behavior**
- pot-stopped should include the pot's jail id in the pot-stopped file.
- start-cleanup should call pot-cmd with an optional jid parameter
- if the jid parameter is given, pot-stop should only operate on pname if the jid matches

### PR DESCRIPTION
**Pull request by pizzamig**
This the potential solution for our concurrency problem.
The new command `pot set-status`, invoked using `lockf`, is used to allow status changes.
start and stop will change status when they start or ends their duties.

It's still very experimental and it needs heavy tests, it's a Sunday night on the couch implementation, so I wouldn't trust it yet.
I started and stopped on pot, so the normal feature seems to be ok.

fix #202

### CODE REVIEW

File: share/pot/start.sh [hunk 1]
```diff
@@ -591,28 +587,58 @@ _js_start()
 	sleep 0.5
 	pkill -f -j "$_pname" "^sleep 1234$"
 
+	# Here is where the pot is started
```
Comment (grembo) [inline share/pot/start.sh:590]: "is started" => "is marked as started"?

**Review by grembo — COMMENTED** [review]
@pizzamig This is a lot of changes and will take some time to review.

One general question: How does this deal with the fact that we can't control when non-persistent jails cleanup their VNET interfaces?

File: share/pot/start.sh (hunk 1 above)
Comment (grembo) [reply share/pot/start.sh:590]: Or has been started?

File: share/pot/set-status.sh [hunk 2]
```diff
@@ -0,0 +1,97 @@
...
+set-status-help()
+{
+	cat <<-"EOH"
+	Internal command, DO NOT USE IF YOU DON'T KNOW WHAT YOU ARE DOING!
+	This command is meant to be invoked using lockf
+	pot set-status [-hv] [-p pname] [-s status]
+	  -h print this help
+	  -v verbose
+	  -p pname : pot name
+	  -s status : he status [starting started stopping stopped]
```
Comment (grembo) [inline share/pot/set-status.sh:16]: he => the

File: share/pot/stop.sh [hunk 3]
```diff
@@ -174,6 +175,12 @@ pot-stop()
 		p)
 			_pname="$OPTARG"
 			;;
+		i)
```
Comment (grembo) [inline share/pot/stop.sh:178]: These should be documented in help (even if marked as internal)

**Review by grembo — COMMENTED** [review]
Some simple remarks already, checking the logic later this week (hopefully)

File: share/pot/start.sh [hunk 4]
```diff
@@ -591,28 +587,58 @@ _js_start()
 	sleep 0.5
 	pkill -f -j "$_pname" "^sleep 1234$"
 
+	# Here is where the pot is makred as started
```
Comment (grembo) [inline share/pot/start.sh:590]: makred => marked

File: share/pot/start.sh [hunk 5]
```diff
@@ -591,28 +587,58 @@ _js_start()
...
+		if [ $rc -eq 2 ]; then
+			_debug "pot $_pname is already stopping (maybe by a pot stop)"
+			return 0
 		fi
-		rm -f "${POT_TMP:-/tmp}/pot_stopped_${_pname}"
-
+		if [ $rc -eq 1 ]; then
+			# should we retry (in case it's stopping?)
+			_error "pot $_pname is not in a state where it can be stopped"
+			# returning, but the situation is quite messed up
```
Comment (grembo) [inline share/pot/start.sh:619]: Again, this would probably mean that it is currently starting?

File: share/pot/stop.sh [hunk 6]
```diff
@@ -5,12 +5,16 @@
 stop-help()
 {
 	cat <<-"EOH"
-	pot stop [-hv] -p potname [pname]
+	pot stop [-hv] [-p] potname
 	  -h print this help
 	  -v verbose
+	  -i interace : network interface (INTERNAL USE ONLY)
```
Comment (grembo) [inline share/pot/stop.sh:11]: interace => interface

File: share/pot/start.sh [hunk 7]
```diff
@@ -690,11 +716,24 @@ pot-start()
 	if ! _is_uid0 ; then
 		return 1
 	fi
-
 	if ! _is_pot_tmp_dir ; then
 		_error "failed to create the POT_TMP directory"
 		return 1
 	fi
+
+	# Here is where the command start
```
[the remark this answers is not in the document]
Comment (grembo) [reply share/pot/start.sh:724]: ("starts" maybe?)

File: share/pot/stop.sh [hunk 8]
```diff
@@ -5,12 +5,16 @@
 stop-help()
 {
 	cat <<-"EOH"
-	pot stop [-hv] -p potname [pname]
+	pot stop [-hv] [-p] potname
```
Comment (grembo) [inline share/pot/stop.sh:8]: This change makes things worse, as you specify the syntax so that: `pot stop -pv potname` should be legal and work (which it won't). Also, the explicit definition of precedence is missing.

Maybe `pot stop [-hv] [-p potname] [potname]` would be more correct (I left "pname" earlier to allow referencing the different parameters).

File: share/pot/start.sh [hunk 9]
```diff
@@ -24,19 +24,17 @@ start-help()
...
 		return
 	fi
-	if [ -n "$2" ] && _is_valid_netif "${2}a" ; then
-		sleep 1 # try to avoid a race condition in the epair driver,
-			# potentially causing a kernel panic, which should
-			# be fixed in FreeBSD 13.1:
-			# https://cgit.freebsd.org/src/commit/?h=stable/13&id=f4aba8c9f0c
-		ifconfig "${2}a" destroy
+	if [ -n "$_iface" ] && _is_valid_netif "$_iface" ; then
+		pot-cmd stop -p "$_pname" -i "$_iface" -s
```
Comment (grembo) [inline share/pot/start.sh:34]: This sends in something like`epair15a`, correct? (this is important for looking at the stop command later).

File: share/pot/stop.sh [hunk 10]
```diff
@@ -29,13 +33,14 @@ _js_cpu_rebalance()
 # $1 pot name
 _js_stop()
 {
-	local _pname _pdir _epair _ip _aname
+	local _pname _pdir _epair _ip _aname _from_start
 	_pname="$1"
+	_from_start="$2"
+	_epair="$3"
```
Comment (grembo) [inline share/pot/stop.sh:39]: When called from start, this interface ends with "a" (like in `epair15a`).

File: share/pot/stop.sh [hunk 11]
```diff
@@ -29,13 +33,14 @@ _js_cpu_rebalance()
...
 	_pdir="${POT_FS_ROOT}/jails/$_pname"
-	_epair=
 	_network_type=$( _get_pot_network_type "$_pname" )
 	if _is_pot_running "$_pname" ; then
-		if _is_pot_vnet "$_pname" ; then
+		if _is_pot_vnet "$_pname" && [ -z "$_epair" ]; then
```
Comment (grembo) [inline share/pot/stop.sh:43]: The interface name determined in here ends on "b" like in `epair15b`
I would suggest to change this to contain epair15a (like the interface that is passed in with the "-i" command line option), like in:

```sh
_epair=$(jexec "$_pname" ifconfig | grep ^epair | cut -d':' -f1)
_epair="${_epair%b}"a
```

File: share/pot/stop.sh [hunk 12]
```diff
@@ -48,40 +53,38 @@ _js_stop()
...
-				_debug "Remove $_ip aliases"
+	fi
+	# those are clean up operations for a pot already stopped
+	if [ -n "$_epair" ]; then
+		_debug "Remove ${_epair%b}[a|b] network interfaces"
+		sleep 1 # try to avoid a race condition in the epair driver,
+				# potentially causing a kernel panic, which should
+				# be fixed in FreeBSD 13.1:
+				# https://cgit.freebsd.org/src/commit/?h=stable/13&id=f4aba8c9f0c
+		ifconfig "${_epair%b}"a destroy
```
Comment (grembo) [inline share/pot/stop.sh:65]: `"${_epair%b}"a` will expand to `epair15aa` when called from start.

In general, I think passing the full interface name of the outer side in the -i parameter to this function makes sense and I would suggest to change this line to `ifconfig "${_epair}" destroy` and move epair interface name modifications up (see comment above).

File: share/pot/stop.sh (hunk 11 above)
Comment (grembo) [reply share/pot/stop.sh:43]: I also think that this should not be done when being called `_from_start` (if start didn't know the correct epair interface name, detecting it will probably make matters worse).

File: share/pot/stop.sh (hunk 6 above)
Comment (grembo) [inline share/pot/stop.sh:11]: Add:

```
-s called from_start (INTERNAL USE ONLY)
```

**Review by grembo — CHANGES_REQUESTED** [review]
Hi @pizzamig 

I finally found some time for a proper review (I haven't _tested_ the changes yet). Most of my comments are obvious I assume.

Just to get this straight: This change implements a locked status change model for pots (all locks involved are per pot), that synchronizes operations on pots.

This should also fix the issue of destroying an epair interface that was re-assigned (as before we had epair destruction in start as well). As far as I follow the logic it should theoretically be impossible now.

What it doesn't fix are the various issues/bugs in vnet/epair that can lead to strange crashes and that become less likely with less concurrency.

Another open question is how to fix a pot that has been stuck in an invalid state (probably manually by the user?).

File: share/pot/set-status.sh [hunk 13]
```diff
@@ -0,0 +1,97 @@
...
+		_error "A pot name is mandatory"
+		set-status-help
+		return 1
+	fi
+	if ! _is_pot "$_pname"; then
+		_error "$_pname is not a pot"
+		return 1
+	fi
+
+	_current_status=$(_get_conf_var "$_pname" "pot.status")
```
[the remark this answers is not in the document]
Comment (grembo) [reply share/pot/set-status.sh:62]: Maybe having something like pot.data would make sense?

File: share/pot/start.sh (hunk 5 above)
Comment (pizzamig) [reply share/pot/start.sh:617]: yes, it's the only case for a -1
I'm assuming that if it's starting (from another invocation) no clean up is needed anymore because the new "starting" has already fixed things.
I cannot really imagine how this can happen, but I want to log it just in case

File: share/pot/start.sh (hunk 7 above)
[the remark this answers is not in the document]
Comment (pizzamig) [reply share/pot/start.sh:722]: I guess: here is where the command "start" starts

File: share/pot/stop.sh (hunk 11 above)
Comment (pizzamig) [reply share/pot/stop.sh:43]: good catch, I'm going to fix the code to always consider `epairNNa`

If `_from_start` is set, but there is no `_iface`, it's very likely that the pot is not running, so it shouldn't enter here.
However, I can add a `[ -z "$_from_start" ]` to avoid surprises

File: share/pot/stop.sh (hunk 12 above)
Comment (pizzamig) [reply share/pot/stop.sh:65]: I'm changing the code to always consider the external epair (a) interface

File: share/pot/set-status.sh (hunk 13 above)
[the remark this answers is not in the document]
Comment (pizzamig) [reply share/pot/set-status.sh:62]: good point. If the machine crashes, the status will be inconsistent.
I guess it could be a follow up activity, there is the need to manage the new files or folder and so on, but it should be implemented soon.
A jail supervisor is somehow needed, but it's something for later (or another life :) )

**Comment by pizzamig** [comment]
I should have addressed the `epair15[a|b]` confusion, moving to always use `a`.
Addressed the other things as well

File: CHANGELOG.md [hunk 14]
```diff
@@ -33,6 +33,7 @@ and this project adheres to [Semantic Versioning](http://semver.org/spec/v2.0.0.
 - fdescfs/procfs: fixed the correcte behavior of those attribute, such as mount them at start
 - mount-out: fix it
 - clone: fix cleanup after failed clone (#214)
+- start/stop: heavy rework to fix concurrency(#202)
```
Comment (grembo) [inline CHANGELOG.md:36]: Space before open parenthesis

File: share/pot/set-status.sh (hunk 13 above)
[the remark this answers is not in the document]
Comment (grembo) [reply share/pot/set-status.sh:62]: @pizzamig We should at least think about the various failure scenarios to make people sure/their pots won't get stuck.

Maybe it would be better to store this in a temporary file, like other things like ".pot_main_pid" (from the signal patch) and then provide a simple command that can be used to remove all of pot's temporary files.

[the remark this answers is not in the document]
Comment (pizzamig) [reply share/pot/set-status.sh]: Using a different file to store the status
I'm unsure about mechanisms to fix situations.
In case of a crash, it's enough to remove the files.
In other cases, you can use the `pot set-status` to fix it, but I would consider it dangerous...

File: share/pot/set-status.sh [hunk 15]
```diff
@@ -0,0 +1,121 @@
...
+# $2 new status
+_set_status()
+{
+	local _pname _status_file _new_status
+	_pname="$1"
+	_new_statu="$2"
+	_status_file="${POT_TMP:-/tmp}/pot_status_${_pname}"
+
+	${SED} -i '' -e "/^pot.status=.*/d" "$_status_file"
+	echo "pot.status=$_new_status" >> "$_status_file"
```
Comment (grembo) [inline share/pot/set-status.sh:44]: The expression should read `-e "/^pot\.status=/d"` (dot needs to be escaped, `.*` not required).

You could change this logic, so it's more atomic (only in combination with `tail -n1` above):

```suggestion
	echo "pot.status=$_new_status" >> "$_status_file"
	# remove first (and outdated) occurrence of pot.status
	${SED} -i '' -n -e ":a" \
	  -e '/^pot\.status=/{n;bc' -e ':c' -e 'p;n;bc' -e '}' \
	  -e "p;n;ba" "$_status_file"
```

Comment (grembo) [reply share/pot/set-status.sh:44]: In case it isn't apparent at first glance, this is how the sed command works:

```perl
# pseudo-code                            # sed

while getline() {                        # a:                    (label a)
    if line.starts_with("pot.status=") { #   /^pot\.status=/{
        next_line();                     #     n
        while getline() {                #     c:                (label c)
            println(line);               #       p
            next_line();                 #       n
        }                                #     bc                (goto c)
        break;                           #     (implicit/eof)
    }                                    #   }
    println(line);                       #   p
    next_line();                         #   n
}                                        # ba                    (goto a)
```

**Review by grembo — COMMENTED** [review]
One typo and two suggestions to make the code a bit more resilient.

**Review by grembo — CHANGES_REQUESTED** [review]
Request changes (as fixing the typo is functionally relevant)

**Comment by grembo** [comment]
@pizzamig Please let me know if anything is unclear, I think this is very close to landing.

File: share/pot/set-status.sh (hunk 15 above)
Comment (pizzamig) [reply share/pot/set-status.sh]: This is brilliant!

**Review by grembo — APPROVED** [review]
I didn’t retest the changes, but to me it looks like all review comments were addressed at this point 👍

**Comment by grembo** [comment]
@pizzamig What about landing this change and start working on new releases for pot and nomad-pot-driver?

**Comment by pizzamig** [comment]
The goal is to make a release before EuroBSD

**Comment by grembo** [comment]
> The goal is to make a release before EuroBSD

Releases I hope (nomad driver too). Then rather sooner than later, so that there are official binaries and we can also deploy it in a staging system and find potential issues.
